### ISSUE TITLE
Run Benchto over HTTPS enabled Presto cluster

### ISSUE THREAD

**Issue by joshuav11** [trinodb/benchto#15]
Hi, I'm getting a `401 Unauthorized` error while trying to execute benchmark over a HTTPS-enabled Presto cluster. I can see that Presto receives the queries from Benchto and runs them without a hitch. I'm thinking that Benchto has troubles getting the metrics/results back. I got this idea because I noticed that we're using two separate Java classes to send (presto driver) and retrieve (benchto-driver) the queries . 

Presto version: 340
Presto authn: via LDAP
Benchmark driver: 340 
I also used the same build to run a benchmark over HTTP and it worked flawlessly. 

```
benchmark-service:
  url: "http://<my-benchto-svc>:8081"
data-sources:
  presto:
    url: jdbc:presto://<presto-url>SSL=true
    username: "<user>"
    password: "<pass>"
    driver-class-name: io.prestosql.jdbc.PrestoDriver
    SSL: true
environment:
  name: <my-env>
presto:
  url: "https://<presto-url>?username=<user>&password=<pass>"
  # username: <user>
  # password: <pass>
benchmark:
  feature:
    presto:
      metrics.collection.enabled: true
macros:
  sleep-4s:
    command: echo "Sleeping for 4s" && sleep 4
```

I think I also got where the error came from. When I try to go to this URL, the browser still asks for my login credentials. After pressing cancel, I get the `Unauthorized` response.
```
https://<presto-url>/v1/query/<query-id>?SSL=true&user=<user>&password=<pass>
```

Can somebody point me to the correct way of doing it? Or is it possible at all? Thanks!
